### ISSUE TITLE
Posting Large Files gives OutofMemoryException

### ISSUE THREAD

**Issue by rs199483** [Vodurden/Http-Multipart-Data-Parser#34]
I posted a 200mb file and it is throwing an error: Exception of type 'System.OutOfMemoryException' was thrown.

>    
StackTrace:
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at HttpMultipartParser.MultipartFormDataParser.<.ctor>b__1(String name, String fileName, String type, String disposition, Byte[] buffer, Int32 bytes) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\MultipartFormDataParser.cs:line 216
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseFilePart(Dictionary`2 parameters, RebufferableBinaryReader reader) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 560
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 705
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 423
   at HttpMultipartParser.StreamingMultipartFormDataParser.Run() in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 239
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\MultipartFormDataParser.cs:line 219
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding) in c:\Users\RKsherman\Downloads\Http-Multipart-Data-Parser-master\Http-Multipart-Data-Parser-master\HttpMultipartParser\MultipartFormDataParser.cs:line 155
   at FileNetRestService.Service1.AddDocument(String appid, String isrecord, Stream stream) in c:\Users\RKsherman\Documents\Workspaces\FileNet\FRD\Code\FileNetRestService\FileNetRestService\FileNetRestService\Service1.svc.cs:line 149

**Comment by rs199483** [comment]
Hold off on this, it may be because I have an older version.  Testing now...

**Comment by rs199483** [comment]
Just tested it with the latest version 2.1.1 and still get error message.

**Comment by rs199483** [comment]
I want to clarify that it is failing on my local 32-bit DEV machine but seems to be ok on a 64-bit server.  Therefore I don't think this is a bug in your software.  Thanks

**Comment by Vodurden** [comment]
Hi rs199483. I'm glad you've got your issue sorted.

From the stack trace you posted it looks like you're using the `MultipartFormDataParser` class. If you want to handle larger files you should use the `StreamingMultipartFormDataParser` class which should be able to handle 200mb files regardless of if you're on a 32-bit or 64-bit machine.

Check out the Readme for an example of how to use it :)

**Comment by rs199483** [comment]
Hi Jake,
I'm not that familiar with lambda expressions.  How do I get the parameters data?  I didn't find any examples of how to do this.

//This gives me an error - Operator '+=' cannot be applied to operands of type 'HttpMultipartParser.StreamingMultipartFormDataParser.ParameterDelegate' and 'lambda expression' 
parser.ParameterHandler += parameter => { jsonprops = parameter[0].Data; };

 Thanks

**Comment by Vodurden** [comment]
The example you've given looks mostly correct. (There's a different error around indexing `parameter` but that shouldn't cause that compile error: The `parameter` field is a single parameter that we've parsed. That callback will be called multiple times as we hit multiple parameters).

To to ensure everything makes sense. What version of C# are you using and what version of this library are you using?

**Comment by rs199483** [comment]
.net 4.5 and the latest version of your library.

**Comment by Vodurden** [comment]
Hmm. That's *very* odd then. We use almost exactly the same fragment inside of https://github.com/Vodurden/Http-Multipart-Data-Parser/blob/master/HttpMultipartParser/MultipartFormDataParser.cs 

Could you post a larger code sample? I wonder if there's some extra context I'm missing.
