### ISSUE TITLE
 System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by lbgaus** [Vodurden/Http-Multipart-Data-Parser#46]
Hi Jake,

I ran across this issue today trying to use the parser. I'm going to take a stab at fixing it, but wanted to post this issue anyway in case you are either faster at fixing it, or know generally why this may be happening.

Here's the stack trace...

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
```

at System.Linq.Enumerable.Skip[TSource](IEnumerable1 source, Int32 count)

at HttpMultipartParser.StreamingMultipartFormDataParser.DetectBoundary(RebufferableBinaryReader reader) in d:\VS Projects\HttpMultipartDataParser\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 312

at HttpMultipartParser.StreamingMultipartFormDataParser.Run() in d:\VS Projects\HttpMultipartDataParser\HttpMultipartParser\StreamingMultipartFormDataParser.cs:line 222

at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize) in d:\VS Projects\HttpMultipartDataParser\HttpMultipartParser\MultipartFormDataParser.cs:line 219

at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream) in d:\VS Projects\HttpMultipartDataParser\HttpMultipartParser\MultipartFormDataParser.cs:line 104

at MultipartMimeParser.MultipartMimeParser.Run()

at MultipartMimeParser.MultipartMimeParser.Main()

**Comment by Vodurden** [comment]
Hi lbgaus,

Thanks for posting an issue! I'm happy for you to take a stab at fixing the issue as nothing immediately pops to mind when I see that error other then a malformed multipart. If you'd like me to take a look could you post a sample input that reproduces the error?

**Comment by ibnuda** [comment]
Sorry to comment on this closed issue.
I have the same problem. On .net461, my code works fine. While on .netcore/.netstandard, I always get this same kind of error.
Here's the code (in F#):
```language=fsharp
let parser = new MultipartFormDataParser (stream) // where the type of stream is Stream
if parser.Files.Count > 0 then
  let file = parser.Files.Item(0)
  let content = file.Data // the type of content is Stream.
  let path = @"C:\tools\"
  use reader = new BinaryReader(content)
  use writer = new FileStream(path, FileMode.CreateNew)
  reader.BaseStream.CopyTo(writer)
```
Response and request headers :
![header](https://user-images.githubusercontent.com/8169908/27914030-2643736e-628c-11e7-9e5a-3d6f5e35dbe8.PNG)
![parameter](https://user-images.githubusercontent.com/8169908/27914037-2bcf59d8-628c-11e7-8e95-157b074d4632.PNG)

The file is written just fine. But there's an exception being thrown when I use it on dotnetcore.

**Comment by ibnuda** [comment]
After looking at the source of MultipartFormDataParser, I tried to use `MultipartFormDataParser(stream, "--")` but got the following exception.
```
  HttpMultipartParser.MultipartParseException: Could not find expected boundary
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize)
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary)
``

**Comment by ibnuda** [comment]
Actually, I'm sorry. The err is in my part. My code (server part) reads the request twice.
You can ignore it.
